name: Release
on:
  create:
jobs:
  build:
    name: "Release: ${{ github.ref }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: contains(github.ref, '/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GHT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
